//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Equipos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioSoap")]
    public interface ServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Consumo.ServiceReference1.HelloWorldResponse HelloWorld(Consumo.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Consumo.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        Consumo.ServiceReference1.SaludarResponse Saludar(Consumo.ServiceReference1.SaludarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> SaludarAsync(Consumo.ServiceReference1.SaludarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerEquiposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        Consumo.ServiceReference1.ObtenerEquiposResponse ObtenerEquipos(Consumo.ServiceReference1.ObtenerEquiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerEquiposResponse> ObtenerEquiposAsync(Consumo.ServiceReference1.ObtenerEquiposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        Consumo.ServiceReference1.GuardarLogResponse GuardarLog(Consumo.ServiceReference1.GuardarLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarLog", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> GuardarLogAsync(Consumo.ServiceReference1.GuardarLogRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        Consumo.ServiceReference1.ObtenerProductosResponse ObtenerProductos(Consumo.ServiceReference1.ObtenerProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductosResponse> ObtenerProductosAsync(Consumo.ServiceReference1.ObtenerProductosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Consumo.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Consumo.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Saludar", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.SaludarRequestBody Body;
        
        public SaludarRequest() {
        }
        
        public SaludarRequest(Consumo.ServiceReference1.SaludarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public SaludarRequestBody() {
        }
        
        public SaludarRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.SaludarResponseBody Body;
        
        public SaludarResponse() {
        }
        
        public SaludarResponse(Consumo.ServiceReference1.SaludarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludarResult;
        
        public SaludarResponseBody() {
        }
        
        public SaludarResponseBody(string SaludarResult) {
            this.SaludarResult = SaludarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquipos", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerEquiposRequestBody Body;
        
        public ObtenerEquiposRequest() {
        }
        
        public ObtenerEquiposRequest(Consumo.ServiceReference1.ObtenerEquiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerEquiposRequestBody {
        
        public ObtenerEquiposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerEquiposResponseBody Body;
        
        public ObtenerEquiposResponse() {
        }
        
        public ObtenerEquiposResponse(Consumo.ServiceReference1.ObtenerEquiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEquiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Consumo.ServiceReference1.Equipos[] ObtenerEquiposResult;
        
        public ObtenerEquiposResponseBody() {
        }
        
        public ObtenerEquiposResponseBody(Consumo.ServiceReference1.Equipos[] ObtenerEquiposResult) {
            this.ObtenerEquiposResult = ObtenerEquiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLog", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarLogRequestBody Body;
        
        public GuardarLogRequest() {
        }
        
        public GuardarLogRequest(Consumo.ServiceReference1.GuardarLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public GuardarLogRequestBody() {
        }
        
        public GuardarLogRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.GuardarLogResponseBody Body;
        
        public GuardarLogResponse() {
        }
        
        public GuardarLogResponse(Consumo.ServiceReference1.GuardarLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarLogResult;
        
        public GuardarLogResponseBody() {
        }
        
        public GuardarLogResponseBody(string GuardarLogResult) {
            this.GuardarLogResult = GuardarLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductos", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerProductosRequestBody Body;
        
        public ObtenerProductosRequest() {
        }
        
        public ObtenerProductosRequest(Consumo.ServiceReference1.ObtenerProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerProductosRequestBody {
        
        public ObtenerProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consumo.ServiceReference1.ObtenerProductosResponseBody Body;
        
        public ObtenerProductosResponse() {
        }
        
        public ObtenerProductosResponse(Consumo.ServiceReference1.ObtenerProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerProductosResult;
        
        public ObtenerProductosResponseBody() {
        }
        
        public ObtenerProductosResponseBody(string ObtenerProductosResult) {
            this.ObtenerProductosResult = ObtenerProductosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSoapChannel : Consumo.ServiceReference1.ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoapClient : System.ServiceModel.ClientBase<Consumo.ServiceReference1.ServicioSoap>, Consumo.ServiceReference1.ServicioSoap {
        
        public ServicioSoapClient() {
        }
        
        public ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.HelloWorldResponse Consumo.ServiceReference1.ServicioSoap.HelloWorld(Consumo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Consumo.ServiceReference1.HelloWorldRequest inValue = new Consumo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceReference1.HelloWorldRequestBody();
            Consumo.ServiceReference1.HelloWorldResponse retVal = ((Consumo.ServiceReference1.ServicioSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> Consumo.ServiceReference1.ServicioSoap.HelloWorldAsync(Consumo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Consumo.ServiceReference1.HelloWorldRequest inValue = new Consumo.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Consumo.ServiceReference1.HelloWorldRequestBody();
            return ((Consumo.ServiceReference1.ServicioSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.SaludarResponse Consumo.ServiceReference1.ServicioSoap.Saludar(Consumo.ServiceReference1.SaludarRequest request) {
            return base.Channel.Saludar(request);
        }
        
        public string Saludar(string nombre) {
            Consumo.ServiceReference1.SaludarRequest inValue = new Consumo.ServiceReference1.SaludarRequest();
            inValue.Body = new Consumo.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            Consumo.ServiceReference1.SaludarResponse retVal = ((Consumo.ServiceReference1.ServicioSoap)(this)).Saludar(inValue);
            return retVal.Body.SaludarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> Consumo.ServiceReference1.ServicioSoap.SaludarAsync(Consumo.ServiceReference1.SaludarRequest request) {
            return base.Channel.SaludarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.SaludarResponse> SaludarAsync(string nombre) {
            Consumo.ServiceReference1.SaludarRequest inValue = new Consumo.ServiceReference1.SaludarRequest();
            inValue.Body = new Consumo.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            return ((Consumo.ServiceReference1.ServicioSoap)(this)).SaludarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.ObtenerEquiposResponse Consumo.ServiceReference1.ServicioSoap.ObtenerEquipos(Consumo.ServiceReference1.ObtenerEquiposRequest request) {
            return base.Channel.ObtenerEquipos(request);
        }
        
        public Consumo.ServiceReference1.Equipos[] ObtenerEquipos() {
            Consumo.ServiceReference1.ObtenerEquiposRequest inValue = new Consumo.ServiceReference1.ObtenerEquiposRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerEquiposRequestBody();
            Consumo.ServiceReference1.ObtenerEquiposResponse retVal = ((Consumo.ServiceReference1.ServicioSoap)(this)).ObtenerEquipos(inValue);
            return retVal.Body.ObtenerEquiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerEquiposResponse> Consumo.ServiceReference1.ServicioSoap.ObtenerEquiposAsync(Consumo.ServiceReference1.ObtenerEquiposRequest request) {
            return base.Channel.ObtenerEquiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerEquiposResponse> ObtenerEquiposAsync() {
            Consumo.ServiceReference1.ObtenerEquiposRequest inValue = new Consumo.ServiceReference1.ObtenerEquiposRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerEquiposRequestBody();
            return ((Consumo.ServiceReference1.ServicioSoap)(this)).ObtenerEquiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.GuardarLogResponse Consumo.ServiceReference1.ServicioSoap.GuardarLog(Consumo.ServiceReference1.GuardarLogRequest request) {
            return base.Channel.GuardarLog(request);
        }
        
        public string GuardarLog(string mensaje) {
            Consumo.ServiceReference1.GuardarLogRequest inValue = new Consumo.ServiceReference1.GuardarLogRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarLogRequestBody();
            inValue.Body.mensaje = mensaje;
            Consumo.ServiceReference1.GuardarLogResponse retVal = ((Consumo.ServiceReference1.ServicioSoap)(this)).GuardarLog(inValue);
            return retVal.Body.GuardarLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> Consumo.ServiceReference1.ServicioSoap.GuardarLogAsync(Consumo.ServiceReference1.GuardarLogRequest request) {
            return base.Channel.GuardarLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.GuardarLogResponse> GuardarLogAsync(string mensaje) {
            Consumo.ServiceReference1.GuardarLogRequest inValue = new Consumo.ServiceReference1.GuardarLogRequest();
            inValue.Body = new Consumo.ServiceReference1.GuardarLogRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((Consumo.ServiceReference1.ServicioSoap)(this)).GuardarLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumo.ServiceReference1.ObtenerProductosResponse Consumo.ServiceReference1.ServicioSoap.ObtenerProductos(Consumo.ServiceReference1.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductos(request);
        }
        
        public string ObtenerProductos() {
            Consumo.ServiceReference1.ObtenerProductosRequest inValue = new Consumo.ServiceReference1.ObtenerProductosRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerProductosRequestBody();
            Consumo.ServiceReference1.ObtenerProductosResponse retVal = ((Consumo.ServiceReference1.ServicioSoap)(this)).ObtenerProductos(inValue);
            return retVal.Body.ObtenerProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductosResponse> Consumo.ServiceReference1.ServicioSoap.ObtenerProductosAsync(Consumo.ServiceReference1.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumo.ServiceReference1.ObtenerProductosResponse> ObtenerProductosAsync() {
            Consumo.ServiceReference1.ObtenerProductosRequest inValue = new Consumo.ServiceReference1.ObtenerProductosRequest();
            inValue.Body = new Consumo.ServiceReference1.ObtenerProductosRequestBody();
            return ((Consumo.ServiceReference1.ServicioSoap)(this)).ObtenerProductosAsync(inValue);
        }
    }
}
